[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.27"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "murky/=lib/murky/",
    "@foundry-devops=lib/foundry-devops/"
]

fs_permissions = [{ access = "read-write", path = "script/target/"}]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
